# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
 if Vagrant.has_plugin?("vagrant-vbguest")
  config.vbguest.auto_update = false
 end
 config.vm.box = "debian/bookworm64"
 config.vm.hostname = "vm-gabrielpalmeira"
 config.vm.network "public_network", bridge: "eno2"
 config.vm.network "private_network", ip: "192.168.56.116"
 config.vm.provider "virtualbox" do |vb|
  vb.memory = "512"
  vb.gui = false
  vb.name = config.vm.hostname
 end
end
