# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
 # General Vagrant VM configuration.
 config.vm.box = "debian/bookworm64"
 config.ssh.insert_key = false
 if Vagrant.has_plugin?("vagrant-vbguest")
  config.vbguest.auto_update = false
 end
 config.vm.synced_folder ".", "/vagrant", disabled: true
 config.vm.provider :virtualbox do |v|
  v.memory = 512
  v.linked_clone = true
  v.check_guest_additions = false
 end
 config.trigger.before :"Vagrant::Action::Builtin::WaitForCommunicator", type: :action do |t|
  t.warn = "Iterrompe o servidor dhcp do virtualbox"
  t.run = {inline: "vboxmanage dhcpserver stop --interface vboxnet0"}
 end
 # File server.
 config.vm.define "arq" do |arq|
  arq.vm.hostname = "arq.gabrielpalmeira.devops"
  arq.vm.network :private_network, ip: "192.168.56.116"
  (0..3).each do |x|
   arq.vm.disk :disk, size: "10GB", name: "disk-#{x}"
  end
  arq.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbooks/conf-dhcp.yml"
  end
 end
 # Database server.
 config.vm.define "db" do |db|
  db.vm.hostname = "db.gabrielpalmeira.devops"
  db.vm.network :private_network, mac: "0800273A0001", type: "dhcp"
 end
 # Application server 1.
 config.vm.define "app1" do |app|
  app.vm.hostname = "app1.gabrielpalmeira.devops"
  app.vm.network :private_network, type: "dhcp"
 end
 # Application server 2.
 config.vm.define "app2" do |app|
  app.vm.hostname = "app2.gabrielpalmeira.devops"
  app.vm.network :private_network, type: "dhcp"
 end
end
